In [1]:
import pymysql

# MySQL 연결
conn = pymysql.connect(host='localhost', user='root', password="1234", charset='utf8')

# MySQL DB 생성
with conn:
  with conn.cursor() as cur:
        cur.execute('CREATE DATABASE stockdb')
        conn.commit()

In [2]:
import pandas as pd

# 주식 데이터 읽어들이기 
df = pd.read_csv('003490.KS.csv')

df

,Date,Open,High,Low,Close,Adj Close,Volume
0,2012-01-02,43669.421875,44318.226563,43170.343750,43419.882813,42977.582031,333348
1,2012-01-03,43819.148438,44817.304688,43819.148438,44617.675781,44163.171875,573328
2,2012-01-04,44917.121094,44917.121094,43968.871094,44318.226563,43866.777344,377210
3,2012-01-05,44318.226563,44517.859375,43220.253906,43918.964844,43471.582031,479516
4,2012-01-06,43469.792969,44018.777344,42621.355469,43070.527344,42631.785156,382597
...,...,...,...,...,...,...,...
2622,2022-08-30,25600.000000,26150.000000,25550.000000,26100.000000,26100.000000,913346
2623,2022-08-31,25950.000000,26850.000000,25850.000000,26850.000000,26850.000000,1993237
2624,2022-09-01,26700.000000,27050.000000,26150.000000,26150.000000,26150.000000,1508726
2625,2022-09-02,26400.000000,26550.000000,25950.000000,26150.000000,26150.000000,969689
2626,2022-09-05,26050.000000,26100.000000,25550.000000,25650.000000,25650.000000,642436

In [3]:
df['1day'] = df.Close.diff(-1).multiply(-1)

df

,Date,Open,High,Low,Close,Adj Close,Volume,1day
0,2012-01-02,43669.421875,44318.226563,43170.343750,43419.882813,42977.582031,333348,1197.792968
1,2012-01-03,43819.148438,44817.304688,43819.148438,44617.675781,44163.171875,573328,-299.449218
2,2012-01-04,44917.121094,44917.121094,43968.871094,44318.226563,43866.777344,377210,-399.261719
3,2012-01-05,44318.226563,44517.859375,43220.253906,43918.964844,43471.582031,479516,-848.437500
4,2012-01-06,43469.792969,44018.777344,42621.355469,43070.527344,42631.785156,382597,-548.984375
...,...,...,...,...,...,...,...,...
2622,2022-08-30,25600.000000,26150.000000,25550.000000,26100.000000,26100.000000,913346,750.000000
2623,2022-08-31,25950.000000,26850.000000,25850.000000,26850.000000,26850.000000,1993237,-700.000000
2624,2022-09-01,26700.000000,27050.000000,26150.000000,26150.000000,26150.000000,1508726,-0.000000
2625,2022-09-02,26400.000000,26550.000000,25950.000000,26150.000000,26150.000000,969689,-500.000000
2626,2022-09-05,26050.000000,26100.000000,25550.000000,25650.000000,25650.000000,642436,NaN

In [4]:
df['2day'] = df.Close.diff(-2).multiply(-1)
df

,Date,Open,High,Low,Close,Adj Close,Volume,1day,2day
0,2012-01-02,43669.421875,44318.226563,43170.343750,43419.882813,42977.582031,333348,1197.792968,898.343750
1,2012-01-03,43819.148438,44817.304688,43819.148438,44617.675781,44163.171875,573328,-299.449218,-698.710937
2,2012-01-04,44917.121094,44917.121094,43968.871094,44318.226563,43866.777344,377210,-399.261719,-1247.699219
3,2012-01-05,44318.226563,44517.859375,43220.253906,43918.964844,43471.582031,479516,-848.437500,-1397.421875
4,2012-01-06,43469.792969,44018.777344,42621.355469,43070.527344,42631.785156,382597,-548.984375,-249.539063
...,...,...,...,...,...,...,...,...,...
2622,2022-08-30,25600.000000,26150.000000,25550.000000,26100.000000,26100.000000,913346,750.000000,50.000000
2623,2022-08-31,25950.000000,26850.000000,25850.000000,26850.000000,26850.000000,1993237,-700.000000,-700.000000
2624,2022-09-01,26700.000000,27050.000000,26150.000000,26150.000000,26150.000000,1508726,-0.000000,-500.000000
2625,2022-09-02,26400.000000,26550.000000,25950.000000,26150.000000,26150.000000,969689,-500.000000,NaN
2626,2022-09-05,26050.000000,26100.000000,25550.000000,25650.000000,25650.000000,642436,NaN,NaN

In [5]:
df['3day'] = df.Close.diff(-3).multiply(-1)
df

,Date,Open,High,Low,Close,Adj Close,Volume,1day,2day,3day
0,2012-01-02,43669.421875,44318.226563,43170.343750,43419.882813,42977.582031,333348,1197.792968,898.343750,499.082031
1,2012-01-03,43819.148438,44817.304688,43819.148438,44617.675781,44163.171875,573328,-299.449218,-698.710937,-1547.148437
2,2012-01-04,44917.121094,44917.121094,43968.871094,44318.226563,43866.777344,377210,-399.261719,-1247.699219,-1796.683594
3,2012-01-05,44318.226563,44517.859375,43220.253906,43918.964844,43471.582031,479516,-848.437500,-1397.421875,-1097.976563
4,2012-01-06,43469.792969,44018.777344,42621.355469,43070.527344,42631.785156,382597,-548.984375,-249.539063,-698.710938
...,...,...,...,...,...,...,...,...,...,...
2622,2022-08-30,25600.000000,26150.000000,25550.000000,26100.000000,26100.000000,913346,750.000000,50.000000,50.000000
2623,2022-08-31,25950.000000,26850.000000,25850.000000,26850.000000,26850.000000,1993237,-700.000000,-700.000000,-1200.000000
2624,2022-09-01,26700.000000,27050.000000,26150.000000,26150.000000,26150.000000,1508726,-0.000000,-500.000000,NaN
2625,2022-09-02,26400.000000,26550.000000,25950.000000,26150.000000,26150.000000,969689,-500.000000,NaN,NaN
2626,2022-09-05,26050.000000,26100.000000,25550.000000,25650.000000,25650.000000,642436,NaN,NaN,NaN

In [6]:
df['4day'] = df.Close.diff(-4).multiply(-1)
df

,Date,Open,High,Low,Close,Adj Close,Volume,1day,2day,3day,4day
0,2012-01-02,43669.421875,44318.226563,43170.343750,43419.882813,42977.582031,333348,1197.792968,898.343750,499.082031,-349.355469
1,2012-01-03,43819.148438,44817.304688,43819.148438,44617.675781,44163.171875,573328,-299.449218,-698.710937,-1547.148437,-2096.132812
2,2012-01-04,44917.121094,44917.121094,43968.871094,44318.226563,43866.777344,377210,-399.261719,-1247.699219,-1796.683594,-1497.238282
3,2012-01-05,44318.226563,44517.859375,43220.253906,43918.964844,43471.582031,479516,-848.437500,-1397.421875,-1097.976563,-1547.148438
4,2012-01-06,43469.792969,44018.777344,42621.355469,43070.527344,42631.785156,382597,-548.984375,-249.539063,-698.710938,-299.445313
...,...,...,...,...,...,...,...,...,...,...,...
2622,2022-08-30,25600.000000,26150.000000,25550.000000,26100.000000,26100.000000,913346,750.000000,50.000000,50.000000,-450.000000
2623,2022-08-31,25950.000000,26850.000000,25850.000000,26850.000000,26850.000000,1993237,-700.000000,-700.000000,-1200.000000,NaN
2624,2022-09-01,26700.000000,27050.000000,26150.000000,26150.000000,26150.000000,1508726,-0.000000,-500.000000,NaN,NaN
2625,2022-09-02,26400.000000,26550.000000,25950.000000,26150.000000,26150.000000,969689,-500.000000,NaN,NaN,NaN
2626,2022-09-05,26050.000000,26100.000000,25550.000000,25650.000000,25650.000000,642436,NaN,NaN,NaN,NaN

In [7]:
df['5day'] = df.Close.diff(-5).multiply(-1)
df

,Date,Open,High,Low,Close,Adj Close,Volume,1day,2day,3day,4day,5day
0,2012-01-02,43669.421875,44318.226563,43170.343750,43419.882813,42977.582031,333348,1197.792968,898.343750,499.082031,-349.355469,-898.339844
1,2012-01-03,43819.148438,44817.304688,43819.148438,44617.675781,44163.171875,573328,-299.449218,-698.710937,-1547.148437,-2096.132812,-1796.687500
2,2012-01-04,44917.121094,44917.121094,43968.871094,44318.226563,43866.777344,377210,-399.261719,-1247.699219,-1796.683594,-1497.238282,-1946.410157
3,2012-01-05,44318.226563,44517.859375,43220.253906,43918.964844,43471.582031,479516,-848.437500,-1397.421875,-1097.976563,-1547.148438,-1147.882813
4,2012-01-06,43469.792969,44018.777344,42621.355469,43070.527344,42631.785156,382597,-548.984375,-249.539063,-698.710938,-299.445313,1347.515625
...,...,...,...,...,...,...,...,...,...,...,...,...
2622,2022-08-30,25600.000000,26150.000000,25550.000000,26100.000000,26100.000000,913346,750.000000,50.000000,50.000000,-450.000000,NaN
2623,2022-08-31,25950.000000,26850.000000,25850.000000,26850.000000,26850.000000,1993237,-700.000000,-700.000000,-1200.000000,NaN,NaN
2624,2022-09-01,26700.000000,27050.000000,26150.000000,26150.000000,26150.000000,1508726,-0.000000,-500.000000,NaN,NaN,NaN
2625,2022-09-02,26400.000000,26550.000000,25950.000000,26150.000000,26150.000000,969689,-500.000000,NaN,NaN,NaN,NaN
2626,2022-09-05,26050.000000,26100.000000,25550.000000,25650.000000,25650.000000,642436,NaN,NaN,NaN,NaN,NaN

In [8]:
df['6day'] = df.Close.diff(-6).multiply(-1)
df

,Date,Open,High,Low,Close,Adj Close,Volume,1day,2day,3day,4day,5day,6day
0,2012-01-02,43669.421875,44318.226563,43170.343750,43419.882813,42977.582031,333348,1197.792968,898.343750,499.082031,-349.355469,-898.339844,-598.894532
1,2012-01-03,43819.148438,44817.304688,43819.148438,44617.675781,44163.171875,573328,-299.449218,-698.710937,-1547.148437,-2096.132812,-1796.687500,-2245.859375
2,2012-01-04,44917.121094,44917.121094,43968.871094,44318.226563,43866.777344,377210,-399.261719,-1247.699219,-1796.683594,-1497.238282,-1946.410157,-1547.144532
3,2012-01-05,44318.226563,44517.859375,43220.253906,43918.964844,43471.582031,479516,-848.437500,-1397.421875,-1097.976563,-1547.148438,-1147.882813,499.078125
4,2012-01-06,43469.792969,44018.777344,42621.355469,43070.527344,42631.785156,382597,-548.984375,-249.539063,-698.710938,-299.445313,1347.515625,1896.500000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2622,2022-08-30,25600.000000,26150.000000,25550.000000,26100.000000,26100.000000,913346,750.000000,50.000000,50.000000,-450.000000,NaN,NaN
2623,2022-08-31,25950.000000,26850.000000,25850.000000,26850.000000,26850.000000,1993237,-700.000000,-700.000000,-1200.000000,NaN,NaN,NaN
2624,2022-09-01,26700.000000,27050.000000,26150.000000,26150.000000,26150.000000,1508726,-0.000000,-500.000000,NaN,NaN,NaN,NaN
2625,2022-09-02,26400.000000,26550.000000,25950.000000,26150.000000,26150.000000,969689,-500.000000,NaN,NaN,NaN,NaN,NaN
2626,2022-09-05,26050.000000,26100.000000,25550.000000,25650.000000,25650.000000,642436,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
df['7day'] = df.Close.diff(-7).multiply(-1)
df

,Date,Open,High,Low,Close,Adj Close,Volume,1day,2day,3day,4day,5day,6day,7day
0,2012-01-02,43669.421875,44318.226563,43170.343750,43419.882813,42977.582031,333348,1197.792968,898.343750,499.082031,-349.355469,-898.339844,-598.894532,-1048.066407
1,2012-01-03,43819.148438,44817.304688,43819.148438,44617.675781,44163.171875,573328,-299.449218,-698.710937,-1547.148437,-2096.132812,-1796.687500,-2245.859375,-1846.593750
2,2012-01-04,44917.121094,44917.121094,43968.871094,44318.226563,43866.777344,377210,-399.261719,-1247.699219,-1796.683594,-1497.238282,-1946.410157,-1547.144532,99.816406
3,2012-01-05,44318.226563,44517.859375,43220.253906,43918.964844,43471.582031,479516,-848.437500,-1397.421875,-1097.976563,-1547.148438,-1147.882813,499.078125,1048.062500
4,2012-01-06,43469.792969,44018.777344,42621.355469,43070.527344,42631.785156,382597,-548.984375,-249.539063,-698.710938,-299.445313,1347.515625,1896.500000,3842.910156
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2622,2022-08-30,25600.000000,26150.000000,25550.000000,26100.000000,26100.000000,913346,750.000000,50.000000,50.000000,-450.000000,NaN,NaN,NaN
2623,2022-08-31,25950.000000,26850.000000,25850.000000,26850.000000,26850.000000,1993237,-700.000000,-700.000000,-1200.000000,NaN,NaN,NaN,NaN
2624,2022-09-01,26700.000000,27050.000000,26150.000000,26150.000000,26150.000000,1508726,-0.000000,-500.000000,NaN,NaN,NaN,NaN,NaN
2625,2022-09-02,26400.000000,26550.000000,25950.000000,26150.000000,26150.000000,969689,-500.000000,NaN,NaN,NaN,NaN,NaN,NaN
2626,2022-09-05,26050.000000,26100.000000,25550.000000,25650.000000,25650.000000,642436,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
df['14day'] = df.Close.diff(-14).multiply(-1)
df

,Date,Open,High,Low,Close,Adj Close,Volume,1day,2day,3day,4day,5day,6day,7day,14day
0,2012-01-02,43669.421875,44318.226563,43170.343750,43419.882813,42977.582031,333348,1197.792968,898.343750,499.082031,-349.355469,-898.339844,-598.894532,-1048.066407,4042.542968
1,2012-01-03,43819.148438,44817.304688,43819.148438,44617.675781,44163.171875,573328,-299.449218,-698.710937,-1547.148437,-2096.132812,-1796.687500,-2245.859375,-1846.593750,2595.210938
2,2012-01-04,44917.121094,44917.121094,43968.871094,44318.226563,43866.777344,377210,-399.261719,-1247.699219,-1796.683594,-1497.238282,-1946.410157,-1547.144532,99.816406,4192.265625
3,2012-01-05,44318.226563,44517.859375,43220.253906,43918.964844,43471.582031,479516,-848.437500,-1397.421875,-1097.976563,-1547.148438,-1147.882813,499.078125,1048.062500,6288.394531
4,2012-01-06,43469.792969,44018.777344,42621.355469,43070.527344,42631.785156,382597,-548.984375,-249.539063,-698.710938,-299.445313,1347.515625,1896.500000,3842.910156,7436.281250
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2622,2022-08-30,25600.000000,26150.000000,25550.000000,26100.000000,26100.000000,913346,750.000000,50.000000,50.000000,-450.000000,NaN,NaN,NaN,NaN
2623,2022-08-31,25950.000000,26850.000000,25850.000000,26850.000000,26850.000000,1993237,-700.000000,-700.000000,-1200.000000,NaN,NaN,NaN,NaN,NaN
2624,2022-09-01,26700.000000,27050.000000,26150.000000,26150.000000,26150.000000,1508726,-0.000000,-500.000000,NaN,NaN,NaN,NaN,NaN,NaN
2625,2022-09-02,26400.000000,26550.000000,25950.000000,26150.000000,26150.000000,969689,-500.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2626,2022-09-05,26050.000000,26100.000000,25550.000000,25650.000000,25650.000000,642436,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
# NA 있는 행 제거 
df.dropna(inplace=True)
df

,Date,Open,High,Low,Close,Adj Close,Volume,1day,2day,3day,4day,5day,6day,7day,14day
0,2012-01-02,43669.421875,44318.226563,43170.343750,43419.882813,42977.582031,333348,1197.792968,898.343750,499.082031,-349.355469,-898.339844,-598.894532,-1048.066407,4042.542968
1,2012-01-03,43819.148438,44817.304688,43819.148438,44617.675781,44163.171875,573328,-299.449218,-698.710937,-1547.148437,-2096.132812,-1796.687500,-2245.859375,-1846.593750,2595.210938
2,2012-01-04,44917.121094,44917.121094,43968.871094,44318.226563,43866.777344,377210,-399.261719,-1247.699219,-1796.683594,-1497.238282,-1946.410157,-1547.144532,99.816406,4192.265625
3,2012-01-05,44318.226563,44517.859375,43220.253906,43918.964844,43471.582031,479516,-848.437500,-1397.421875,-1097.976563,-1547.148438,-1147.882813,499.078125,1048.062500,6288.394531
4,2012-01-06,43469.792969,44018.777344,42621.355469,43070.527344,42631.785156,382597,-548.984375,-249.539063,-698.710938,-299.445313,1347.515625,1896.500000,3842.910156,7436.281250
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2608,2022-08-09,25850.000000,26000.000000,25650.000000,25900.000000,25900.000000,1154188,-350.000000,50.000000,300.000000,700.000000,1100.000000,600.000000,300.000000,200.000000
2609,2022-08-10,25850.000000,25950.000000,25450.000000,25550.000000,25550.000000,893771,400.000000,650.000000,1050.000000,1450.000000,950.000000,650.000000,300.000000,1300.000000
2610,2022-08-11,25900.000000,25950.000000,25750.000000,25950.000000,25950.000000,935164,250.000000,650.000000,1050.000000,550.000000,250.000000,-100.000000,-650.000000,200.000000
2611,2022-08-12,26050.000000,26200.000000,25850.000000,26200.000000,26200.000000,1241748,400.000000,800.000000,300.000000,-0.000000,-350.000000,-900.000000,-300.000000,-50.000000
2612,2022-08-16,26450.000000,27050.000000,26250.000000,26600.000000,26600.000000,2192305,400.000000,-100.000000,-400.000000,-750.000000,-1300.000000,-700.000000,-400.000000,-950.000000

In [ ]:
pip install pymysql

In [ ]:
pip install sqlalchemy

In [12]:
from sqlalchemy import create_engine
import pymysql

db_config = 'mysql+pymysql://root:1234@localhost:3306/stockdb'
conn = create_engine(db_config).connect()

In [13]:
df.to_sql(name='koreanair20122017', con=conn, if_exists='fail', index=False)

2613