In [8]:
from pymongo import MongoClient
import pandas as pd

client = MongoClient(host='localhost', port=27017)

db = client['news_db']

collection = db.news_info

df = pd.DataFrame(list(collection.find()))

df.drop('_id', axis=1, inplace=True)

df

,date,publisher,title,content,url
0,2002.01.01.,한국경제,[애널리스트가 뽑은 유망주] 삼성전자.SK텔 등 '1등株' 사라,\t'새해에는 이런 종목을 사라'한국경제신문이 뽑은 베스트 애널리스트들은 새해 유망...,https://news.naver.com/main/read.naver?mode=LS...
1,2002.01.02.,매일경제,[부음] 李相增씨(삼성중공업 부장) 모친상,"\t▲李相增(삼성중공업 부장) 相正씨(외환은행 부천 지점장) 모친상, 金榮煥(한국세...",https://news.naver.com/main/read.naver?mode=LS...
2,2002.01.02.,동아일보,[경제 포커스]재계 새해 화두는 '글로벌+경쟁력',\t경제계는 2일 일제히 시무식과 신년 하례식을 갖고 새해 업무에 들어갔다.주요 대...,https://news.naver.com/main/read.naver?mode=LS...
3,2002.01.02.,동아일보,[부음]박중원씨 별세外,\t◇朴重源씨(동아일보 제2광고 부장)별세·正植(동양기전㈜ 관리팀 사원)明植씨(부천...,https://news.naver.com/main/read.naver?mode=LS...
4,2002.01.02.,동아일보,[부산/경남]김해공항 해외직항로 활짝 열렸다,\t월드컵과 아시아경기대회를 앞두고 김해국제공항의 해외직항로가 대폭 확충된다.2일 ...,https://news.naver.com/main/read.naver?mode=LS...
...,...,...,...,...,...
382505,2021.09.23.,아시아투데이,"프로배구, 2021-2022 신인드래프트 28일 개최",관련사진 (1)0/제공=KOVO 한국배구연맹(KOVO)이 오는 28일 오후 2시 서...,https://www.asiatoday.co.kr/view.php?key=20210...
382506,2021.09.23.,중소기업신문,국내 항공사 보유 항공기 2년 새 42대 줄었다,코로나로 국내 항공사 보유 항공기 수 감소. 사진/연합뉴스 코로나19 팬데믹 여파가...,http://www.smedaily.co.kr/news/articleView.htm...
382507,2021.09.23.,엑스포츠뉴스,"KOVO, 2021~2022 남자부 신인선수 드래프트 28일 실시",(엑스포츠뉴스 조은혜 기자) 한국배구연맹(KOVO)은 28일 오후 2시 청담 리베라...,https://www.xportsnews.com/?ac=article_view&en...
382508,2021.09.23.,금강일보,[오후 포털사이트 상위 검색 순위] '2차전지 관련주' 에코프로비엠 상승세로 장 마감,에코프로비엠이 상승세를 보여 투자자들의 눈길을 모으고 있다. 23일 에코프로비엠은 ...,http://www.ggilbo.com/news/articleView.html?id...
382509,2021.09.23.,미디어펜,[마감시황]'헝다 쇼크'에도 코스피 0.4% 하락 그쳐,이날 유가증권시장에서 코스피 지수는 전일 대비 12.93포인트(-0.41%) 하락한...,http://www.mediapen.com/news/view/665304

In [9]:
df.drop_duplicates(inplace=True)
df

,date,publisher,title,content,url
0,2002.01.01.,한국경제,[애널리스트가 뽑은 유망주] 삼성전자.SK텔 등 '1등株' 사라,\t'새해에는 이런 종목을 사라'한국경제신문이 뽑은 베스트 애널리스트들은 새해 유망...,https://news.naver.com/main/read.naver?mode=LS...
1,2002.01.02.,매일경제,[부음] 李相增씨(삼성중공업 부장) 모친상,"\t▲李相增(삼성중공업 부장) 相正씨(외환은행 부천 지점장) 모친상, 金榮煥(한국세...",https://news.naver.com/main/read.naver?mode=LS...
2,2002.01.02.,동아일보,[경제 포커스]재계 새해 화두는 '글로벌+경쟁력',\t경제계는 2일 일제히 시무식과 신년 하례식을 갖고 새해 업무에 들어갔다.주요 대...,https://news.naver.com/main/read.naver?mode=LS...
3,2002.01.02.,동아일보,[부음]박중원씨 별세外,\t◇朴重源씨(동아일보 제2광고 부장)별세·正植(동양기전㈜ 관리팀 사원)明植씨(부천...,https://news.naver.com/main/read.naver?mode=LS...
4,2002.01.02.,동아일보,[부산/경남]김해공항 해외직항로 활짝 열렸다,\t월드컵과 아시아경기대회를 앞두고 김해국제공항의 해외직항로가 대폭 확충된다.2일 ...,https://news.naver.com/main/read.naver?mode=LS...
...,...,...,...,...,...
382505,2021.09.23.,아시아투데이,"프로배구, 2021-2022 신인드래프트 28일 개최",관련사진 (1)0/제공=KOVO 한국배구연맹(KOVO)이 오는 28일 오후 2시 서...,https://www.asiatoday.co.kr/view.php?key=20210...
382506,2021.09.23.,중소기업신문,국내 항공사 보유 항공기 2년 새 42대 줄었다,코로나로 국내 항공사 보유 항공기 수 감소. 사진/연합뉴스 코로나19 팬데믹 여파가...,http://www.smedaily.co.kr/news/articleView.htm...
382507,2021.09.23.,엑스포츠뉴스,"KOVO, 2021~2022 남자부 신인선수 드래프트 28일 실시",(엑스포츠뉴스 조은혜 기자) 한국배구연맹(KOVO)은 28일 오후 2시 청담 리베라...,https://www.xportsnews.com/?ac=article_view&en...
382508,2021.09.23.,금강일보,[오후 포털사이트 상위 검색 순위] '2차전지 관련주' 에코프로비엠 상승세로 장 마감,에코프로비엠이 상승세를 보여 투자자들의 눈길을 모으고 있다. 23일 에코프로비엠은 ...,http://www.ggilbo.com/news/articleView.html?id...
382509,2021.09.23.,미디어펜,[마감시황]'헝다 쇼크'에도 코스피 0.4% 하락 그쳐,이날 유가증권시장에서 코스피 지수는 전일 대비 12.93포인트(-0.41%) 하락한...,http://www.mediapen.com/news/view/665304

In [3]:
# import pymysql

# # MySQL 연결
# conn = pymysql.connect(host='localhost', user='root', password="1234", charset='utf8')

# # MySQL DB 생성
# with conn:
#     with conn.cursor() as cur:
#         cur.execute('CREATE DATABASE newsdb')
#         conn.commit()

In [14]:
from sqlalchemy import create_engine
import pymysql

db_config = 'mysql+pymysql://root:1234@localhost:3306/newsdb'
conn = create_engine(db_config).connect()

In [11]:
df['date'] = pd.to_datetime(df['date'])

df

,date,publisher,title,content,url
0,2002-01-01,한국경제,[애널리스트가 뽑은 유망주] 삼성전자.SK텔 등 '1등株' 사라,\t'새해에는 이런 종목을 사라'한국경제신문이 뽑은 베스트 애널리스트들은 새해 유망...,https://news.naver.com/main/read.naver?mode=LS...
1,2002-01-02,매일경제,[부음] 李相增씨(삼성중공업 부장) 모친상,"\t▲李相增(삼성중공업 부장) 相正씨(외환은행 부천 지점장) 모친상, 金榮煥(한국세...",https://news.naver.com/main/read.naver?mode=LS...
2,2002-01-02,동아일보,[경제 포커스]재계 새해 화두는 '글로벌+경쟁력',\t경제계는 2일 일제히 시무식과 신년 하례식을 갖고 새해 업무에 들어갔다.주요 대...,https://news.naver.com/main/read.naver?mode=LS...
3,2002-01-02,동아일보,[부음]박중원씨 별세外,\t◇朴重源씨(동아일보 제2광고 부장)별세·正植(동양기전㈜ 관리팀 사원)明植씨(부천...,https://news.naver.com/main/read.naver?mode=LS...
4,2002-01-02,동아일보,[부산/경남]김해공항 해외직항로 활짝 열렸다,\t월드컵과 아시아경기대회를 앞두고 김해국제공항의 해외직항로가 대폭 확충된다.2일 ...,https://news.naver.com/main/read.naver?mode=LS...
...,...,...,...,...,...
382505,2021-09-23,아시아투데이,"프로배구, 2021-2022 신인드래프트 28일 개최",관련사진 (1)0/제공=KOVO 한국배구연맹(KOVO)이 오는 28일 오후 2시 서...,https://www.asiatoday.co.kr/view.php?key=20210...
382506,2021-09-23,중소기업신문,국내 항공사 보유 항공기 2년 새 42대 줄었다,코로나로 국내 항공사 보유 항공기 수 감소. 사진/연합뉴스 코로나19 팬데믹 여파가...,http://www.smedaily.co.kr/news/articleView.htm...
382507,2021-09-23,엑스포츠뉴스,"KOVO, 2021~2022 남자부 신인선수 드래프트 28일 실시",(엑스포츠뉴스 조은혜 기자) 한국배구연맹(KOVO)은 28일 오후 2시 청담 리베라...,https://www.xportsnews.com/?ac=article_view&en...
382508,2021-09-23,금강일보,[오후 포털사이트 상위 검색 순위] '2차전지 관련주' 에코프로비엠 상승세로 장 마감,에코프로비엠이 상승세를 보여 투자자들의 눈길을 모으고 있다. 23일 에코프로비엠은 ...,http://www.ggilbo.com/news/articleView.html?id...
382509,2021-09-23,미디어펜,[마감시황]'헝다 쇼크'에도 코스피 0.4% 하락 그쳐,이날 유가증권시장에서 코스피 지수는 전일 대비 12.93포인트(-0.41%) 하락한...,http://www.mediapen.com/news/view/665304

In [ ]:
for i in range(2002, 2022):
    df_year = df[df['date'].dt.year == i]
    df_year.to_json(f'../data/news_data/news_{i}.json',orient = 'records',force_ascii=False)